version: "3.1"

services:
  rabbitmq:
    hostname: "rabbit_node_dnd"
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:5.0.3-alpine
    hostname: "redis_node_dnd"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  app:
    build: .
    hostname: "app_node_dnd"
    ports:
      - "8080:3300"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
      - mongobd

  mongobd:
    image: mongo:4.0.4
    hostname: "mongodb_node_dnd"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
