version: "3.1"

services:
  rabbitmq:
    hostname: "rabbit_node_dnd"
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

  redis_insight:
    image: redislabs/redisinsight:latest
    restart: always
    hostname: "redis_insight_node_dnd"
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_volume_data:/db

  app:
    build: .
    hostname: "app_node_dnd"
    ports:
      - "8080:8080"
    volumes:
      - .:/apidnddemo
    depends_on:
      - rabbitmq
      - redis
      - mongodb
      - redis_insight

  mongodb:
    image: mongo:7.0
    hostname: "mongodb_node_dnd"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apidndfullstack
      - MONGO_INITDB_ROOT_PASSWORD=tfNqdeoeN8u.
volumes:
  mongodata:
    driver: local
  redis_volume_data:
    driver: local
  redis_insight_volume_data:
    driver: local
